#!/usr/bin/env bash
# Verify pitstop generates clean output for all forks.
#
# Usage:
#   ./scripts/verify_forks.sh <client> <source_file>
#
# Examples:
#   ./scripts/verify_forks.sh geth /path/to/protocol_params.go
#   ./scripts/verify_forks.sh nethermind /path/to/GasCostOf.cs

set -euo pipefail

if [[ $# -lt 2 ]]; then
  echo "Usage: $0 <client> <source_file>"
  exit 1
fi

CLIENT="$1"
SOURCE="$2"

if [[ ! -f "$SOURCE" ]]; then
  echo "Source file not found: $SOURCE"
  exit 1
fi

cd "$(dirname "$0")/.."
FORKS_FILE="schedules/forks.yaml"

# Read fork names from forks.yaml (in definition order)
FORKS=$(grep -E '^\s{2}\w' "$FORKS_FILE" | sed 's/:.*//' | tr -d ' ')

TMPDIR=$(mktemp -d)
trap 'rm -rf "$TMPDIR"' EXIT

PASS=0
FAIL=0

for fork in $FORKS; do
  # Determine file extension from source file
  ext="${SOURCE##*.}"
  output="$TMPDIR/${fork}.${ext}"

  if ! uv run pitstop swap "$CLIENT" "$fork" "$output" >/dev/null 2>"$TMPDIR/err"; then
    echo "FAIL $fork — $(cat "$TMPDIR/err")"
    FAIL=$((FAIL + 1))
    continue
  fi

  # Get diff, ignoring pitstop header additions
  raw_diff=$(diff "$SOURCE" "$output" 2>&1 || true)

  # Strip pitstop header lines from diff
  real_diff=$(echo "$raw_diff" \
    | grep "^[<>]" \
    | grep -v "Code generated by pitstop" \
    | grep -v "^> //$" \
    || true)

  if [[ -z "$real_diff" ]]; then
    echo "  OK  $fork"
    PASS=$((PASS + 1))
  else
    # Check if the "new" lines only contain empty values (expected for older forks).
    # Empty patterns: "= ;" / "= ;  //" / "uint64 =  //" / "= uint64() //"
    new_lines=$(echo "$real_diff" | grep "^>" || true)
    has_real_value=$(echo "$new_lines" | grep -E '= [0-9]|= \$|uint64\([0-9]' || true)

    if [[ -z "$has_real_value" ]]; then
      count=$(echo "$new_lines" | wc -l)
      echo "  OK  $fork ($count expected empty)"
      PASS=$((PASS + 1))
    else
      echo "FAIL $fork"
      echo "$raw_diff" | head -30
      FAIL=$((FAIL + 1))
    fi
  fi
done

echo ""
echo "Results: $PASS passed, $FAIL failed"
exit $FAIL
